coduno/api

coduno.go, controllers/code.go, controllers/company.go, controllers/fingerprint.go, controllers/token.go, models/challenge.go, models/coder.go, models/company.go, models/fingerprint.go, models/template.go
* Add all the models
* Add session cookie
* Modify CORS
* Add company and fingerprint controllers
=> models ,ctrl ,sec ,dep, sess

coduno.go, controllers/challenge.go, controllers/token.go, models/challenge.go, models/company.go, util/http.go
* Refactor models save method
* Add handler for getting the engine url
* Add webInterface, runner, flags and languages
to challenge
* Refactor the mockData method
=> models, ctrl

controllers/challenge.go, controllers/company.go, controllers/fingerprint.go, controllers/mock.go, controllers/submission.go, controllers/task.go, main.go
* Add /task/{id} route
* Add /results/{id}/submissions route
* Add mocked data
* Enable cors when engine.IsDevAppServer
=> ctrl: Submission, Task, Mock, sec: cors

.gitignore, controllers/challenge.go, controllers/result.go, main.go
api endpoints for: 
- GET /challenge/{id}
- GET /companies/{id}/challenge
- POST /result
=> create api endpoints

controllers/challenge.go, controllers/code.go, controllers/company.go, controllers/invitation.go, controllers/status.go, controllers/submission.go, controllers/task.go, mail/template.subscription, main.go
* Guard checks all the requests for errors
=> Add request guard

controllers/mock.go, controllers/submission.go, main.go
* Post on engine when receiving a submission that
has code
* Submission is not created because the response
from docker is just redirected to the client
=> hack, ctrl: Mock, Submission

controllers/code.go, controllers/company.go, controllers/engine.go, controllers/submission.go, mail/mail.go
=> ctrl: Code, Company, Engine, Submission. mail

controllers/challenge.go, controllers/invitation.go, controllers/mock.go, controllers/profile.go, controllers/result.go, controllers/submission.go, controllers/task.go, controllers/user.go, util/passenger/passenger.go
* move passenger from engine to app
* refactor imports
=> Refactor dependencies

controllers/mock.go, controllers/result.go, controllers/submission.go, controllers/task.go, main.go
* Create actually code tasks in mock ctrl
* Add error handle in result ctrl
* Add TODO in submission ctrl
* Load task by type too in task ctrl
* Fix passenger import in main
=> fixes in ctrl: Mock, Result, Submission, task

controllers/mock.go, main.go
* Add function to mock ccc
* Fix cors
=> ctrl: Mock

controllers/result.go
* Check if a result for the (user, challenge)
combination already exists before saving
=> ctrl: Result

controllers/user.go
* Add GET method for /users
* Get all the users with their state
(invited, coding) if the user is a company
=> ctrl: User

controllers/invitation.go, controllers/mock.go, controllers/result.go, controllers/submission.go, util/password/password.go
* Add parrent to access token in ctrl.invitation
* Add languages in tasks from ctrl.mock
* Add startTimes in ctrl.CreateResult
* Fix problems in ctrl.submission
* Fix password generation in util.password
=> fix ctrl: invitation, mock, result, submission

controllers/submission.go, runner/javaut.go, runner/runner.go, runner/simple.go
* Split into different components
* Introduced:
- JunitRunner
- JunitSubmission
- SimpleRunner
=> Refactor code submission

model/diff_submission.go, model/diff_submission_impl.go, model/junit_submission.go, runner/diff.go, runner/runner.go
* Add diff runner
* Introduces
- model/diff_submission
- runner/diff
=> model: diff_submission, junit_submission

controllers/result.go, controllers/submission.go, main.go
* set final submissions to a result
=> Create final result

controllers/access_token.go, controllers/invitation.go, controllers/mock.go, controllers/submission.go, controllers/user.go, model/access_token.go, util/passenger/passenger.go
I restructured token authentication and caching. Lots of new stuff moved to passenger. Security was improved by hashing tokens.
=> Rewrite of token authentication

controllers/result.go, controllers/submission.go, main.go, runner/runner.go
* Add possibility to finish a task by setting the
final submission in the result
=> ctrl: Result, Submission

controllers/result.go, main.go
* save the result when setting final submissions
* simple get for companies
=> Fix result endpoint

controllers/profile.go, controllers/result.go, controllers/user.go, main.go, model/result.go
* Add started and finished time to result
* Add get /users/{key} route
* Add get last challenges for profile
* Refactor get result method
* Fixes #46
=> ctrl: profile, result, user; model: result

controllers/result.go, logic/logic.go, model/challenge.go, model/logic.go, model/result.go, model/skills.go, model/task.go
This is a first implementation for #42 to be reviewed. Currently, it will panic, because no `Tasker`s have been defined.
=> logic: Sketch implementation

controllers/mock.go, runner/javaut.go, runner/runner.go, runner/simple.go, test/junit.go
* Create JUnit runner
* Create JUnit tester
=> Add support for JUnit runs

controllers/mock.go, main.go
Contains the following tasks
* hello-world
* fizzbuzz
* ngram
=> Create a real challenge

.dockerignore, Dockerfile
Generated by
gcloud preview app gen-config
Important changes see
https://groups.google.com/forum/#!topic/google-appengine-go/D7eytg7btr8
=> gae: Update Dockerfile and add .dockerignore

controllers/mock.go, runner/diff.go, runner/simple.go, test/diff.go, test/io.go, test/junit.go, test/simple.go, test/test.go, util/cloud.go, util/storage.go
* Create the runner and tester
* Refactor the simple runner
Superseded #66
=> Add diff runner and tester

controllers/mock.go, controllers/submission.go, model/test_stats.go, runner/diff.go, test/diff.go, test/io.go, test/junit.go, test/simple.go, test/test.go
* Run one test at a time
* Return test status instead of test results
* Persist test results in runners
=> Refactor the testers and runners

controllers/task.go, main.go
* Add TestsByTaskKey in task ctrl
=> Get tests for task

controllers/mock.go, model/coder_junit_result.go, model/coder_junit_result_impl.go, runner/javaut.go, test/coder_junit.go, test/junit.go, test/test.go, util/storage.go
* modify javaut runner so it can run unit tests either from coduno or users
* add tester for unit tests written by users
* create basic task for this purpose(unit testing an isPrime method)
=> Add tester for unit tests

controllers/mock.go, test/coder_junit.go
* only send relevant part of result to coder
* change web interface for this type of task
=> Change result display for coder junit

runner/diff.go, runner/runner.go
fully tested with our current challenges, will merge tomorrow noon unless someone flames
=> Docker: disable networking for challenges
